[workspace]
resolver = "3"
members = ["crates/*"]


[workspace.dependencies]
bevy = "0.17"

[workspace.dependencies.tracing]
version = "0.1"
features = [
    "max_level_debug",
    "release_max_level_warn",
]
