[package]
name = "console"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
tracing.workspace = true
crossbeam = "0.8"
chrono = "0.4"

# example dependencies
[dev-dependencies]
purple = { path = "../purple" }

[[example]]
name = "basic"
path = "examples/basic.rs"
